openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags:
  - name: Products
paths:
  /test:
    get:
      summary: djkdjf
      description: djfkdjkj
      tags:
        - "Products"
      parameters:
        - in: query
          description: djhfjdshn
          name: djkdjf
          schema:
            $ref: '#/components/schemas/company'


      responses:
        '200':
          description: OK

components:
  schemas:    
    company:
      type: string
      enum:
        - djdjdjd
        - dvdhvbhf
        - ddfhfh
  